export const types =
{
    //GLOBAL
    GLOBAL_LOGIN: "GLOBAL_LOGIN",
    GLOBAL_INITING: "GLOBAL_INITING",
    GLOBAL_INIT: "GLOBAL_INIT",

    //USUARIOS
    USUARIOS_SAVE: "USUARIOS_SAVE"
}